version: "3.8"

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    image: gila-notification-api
    container_name: gila-api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    restart: always
    environment:
      MONGO_URI: mongodb://mongodb:27017/gila-notifications
    networks:
      - app-network

  app:
    image: gila-notification-ui
    container_name: gila-ui
    ports:
      - 3000:3000
    depends_on:
      - api
    restart: always
    environment:
      API_URL: http://api:8080/api
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network: {}
